#!/bin/bash

usage() {
	cat - <<EOM
$(basename $0): A terrible tool for LRU caching.
	$(basename $0) <cache name>
	$(basename $0) <cache name> <hit value>
EOM
}

cache-read() {
	if [ -f "$cachefile" ]; then
		tac "$cachefile"
	fi
}

cache-hit() {
	touch "$cachefile"
	tmpfile="$cachedir/.tmpfile"
	grep -v "^${value}\$" "$cachefile" > "$tmpfile"
	mv "$tmpfile" "$cachefile"
	echo "$value" >> "$cachefile"
}

cachedir=${CTHLRU_CACHE:-"$HOME/.cthlru"}

	if [ -z "$1" ]; then
		usage
		exit
	fi

cachefile="$cachedir/$1"

if [ ! -d "$cachedir" ]; then
	mkdir -p "$cachedir"
fi

if [ -n "$2" ]; then
	value="$2"
	cache-hit
else
	cache-read
fi
